### ISSUE TITLE
Support incremental build

### ISSUE THREAD

**Issue by chm-tm** [saucecontrol/InheritDoc#12]
The current build integration lets the `_InheritDocPostProcess` task run regardless of whether the C# compiler ran.

In case of an incremental build where the task's output is up to date with regard to its inputs, post processing should be omitted in order to minimize build time. This can save quite a lot of time for large projects.

I've got a modified `.targets` file working which sets the `CopyDocumentationFileToOutputDirectory` property to `false` and uses both the `DocFileItem` and `FinalDocFile` items to get this right.

**Comment by saucecontrol** [comment]
Fixed in #13

**Comment by chm-tm** [comment]
Updating to 2.0.0 saves about 30% of the CI build time in my current project. I'm very happy!
