### ISSUE TITLE
Bug with Id for explicit Implementations from Type with multiple Generics

### ISSUE THREAD

**Issue by Herrmel** [saucecontrol/InheritDoc#5]
Hello, first off thank you for this project. I really dont understand why there is no Tool that uses the same base as Intellisense currently does to provide the functionality of inheritdoc so I'm really glad for this project.

I think I found a bug in generating the Id for Explicit Property Implementation.  I implemented a class that implements `IDictionary` and explicitly implementent some stuff like the Property `Keys`. When using this class your Tool reports the error:  `IDT003: Cref not present and no base could be found for: P:ImplementsIDicitionary.System#Collections#Generic#IDictionary{System#String,System#String}#Keys.`

I debugged this in your Testproject and found out that in `docMap`(`InheritDocProcessor` in Line 253) there is a existing Key with a minor Difference: `P:ImplementsIDicitionary.System#Collections#Generic#IDictionary{System#String@System#String}#Keys`

As you can see the `,` between TypeArguments is replaced with `@` wich I guess comes from `encodeMemberName`(`CecilExtensions` in line 196) thats used in some `GetDocId`-Methods. Since I don't want to break anything (and you probably know the usecases of the replacement better than I do) I would prefer your help on this.

For Testing you can insert the following code in `DocTests.cs`:
```csharp
/// <inheritdoc cref="IDictionary{TKey, TValue}"/>
public class ImplementsIDicitionary : IDictionary<string, string>
{
	
	/// <inheritdoc />
	ICollection<string> IDictionary<string, string>.Keys => Keys;

	/// <inheritdoc />
	void IDictionary<string, string>.Add(string key, string value)
	{
		throw new NotImplementedException();
	}
	
	#region UntestedMembers
	/// <inheritdoc />
	ICollection<string> IDictionary<string, string>.Values => Values;
	/// <inheritdoc />
	public int Count => throw new NotImplementedException();
	/// <inheritdoc />
	public string this[string key] { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
	/// <inheritdoc />
	public bool IsReadOnly => throw new NotImplementedException();
	/// <inheritdoc />
	public void Add(KeyValuePair<string, string> item)
	{
		throw new NotImplementedException();
	}
	/// <inheritdoc />
	public void Clear()
	{
		throw new NotImplementedException();
	}
	/// <inheritdoc />
	public bool Contains(KeyValuePair<string, string> item)
	{
		throw new NotImplementedException();
	}
	/// <inheritdoc />
	public bool ContainsKey(string key)
	{
		throw new NotImplementedException();
	}
	/// <inheritdoc />
	public void CopyTo(KeyValuePair<string, string>[] array, int arrayIndex)
	{
		throw new NotImplementedException();
	}
	/// <inheritdoc />
	public IEnumerator<KeyValuePair<string, string>> GetEnumerator()
	{
		throw new NotImplementedException();
	}
	/// <inheritdoc />
	public bool Remove(string key)
	{
		throw new NotImplementedException();
	}
	/// <inheritdoc />
	public bool Remove(KeyValuePair<string, string> item)
	{
		throw new NotImplementedException();
	}
	/// <inheritdoc />
	public bool TryGetValue(string key, out string value)
	{
		throw new NotImplementedException();
	}
	/// <inheritdoc />
	IEnumerator IEnumerable.GetEnumerator()
	{
		throw new NotImplementedException();
	}
	#endregion
}
```
and the following TestMethods to `InheritDocTests.cs`:
```csharp
	[TestMethod]
	public void ExlicitProperty()
	{
		var ele = getDocElement("P:ImplementsIDicitionary.System#Collections#Generic#IDictionary{System#String,System#String}#Keys", "summary");
		Assert.IsNotNull(ele);
	}

	[TestMethod]
	public void ExlicitMethod()
	{
		var ele = getDocElement("M:ImplementsIDicitionary.System#Collections#Generic#IDictionary{System#String,System#String}#Add(System.String,System.String)", "summary");
		Assert.IsNotNull(ele);
	}
```

**Comment by saucecontrol** [comment]
Hey, thanks for the detailed write-up and test cases! I'll give that a look sometime this week.

**Comment by saucecontrol** [comment]
From what I can see in the NETStandard docs, the rule seems to be that the generic parameter *names* are separated by `@` in the DocID when the generic is open, as in `P:System.Collections.Generic.Dictionary`2.System#Collections#Generic#IDictionary{TKey@TValue}#Keys`, but when the generic is closed, the syntax changes to separate the parameter *types* with `,`.  I'll have to verify that in the Roslyn code, but it should be an easy fix :)

**Comment by saucecontrol** [comment]
Never mind, not that simple.  Roslyn inserts `,` whether the generic is open or closed.  But the XML docs that ship with NETStandard, NetFX, and NetCore all use the `@` separator.  It looks like it's either a Roslyn bug or a bug in whatever tool they use to generate the docs they ship in the NuGet packages...  So there's a 50% chance my code is right already 😆

**Comment by Herrmel** [comment]
Seems like our issue is not important enough for them 😞

**Comment by saucecontrol** [comment]
So... it looks like they can't fix that on the Roslyn side, which means I'll have to do a fairly major overhaul of the way I generate documentation IDs to allow it to generate a list of match candidates instead of a single ID.  This was kind of on my todo list already because once Roslyn defines a syntax for function pointer IDs (https://github.com/dotnet/roslyn/issues/48363), it's likely to be different from MSVC's around the way calling conventions are encoded.  Was just putting it off until they actually get around to defining them.  I'll see if I can get something worked out in the next few weeks.

**Comment by Herrmel** [comment]
Ok, thank you very much!

**Comment by saucecontrol** [comment]
Got this fixed and a new version pushed.  Of course I only realized after I had made the changes to support both ID encoding variants that there's no possible way to inherit from a member with the encoding they use in the shipping docs since explicit interface implementation members are implicitly private.  Oh well, I fixed another bug while I was re-writing, and now I'm set up for whatever Roslyn does with function pointers 🤣

**Comment by Herrmel** [comment]
Thank you, works like a charm 👌
Actually I have another small featurerequest but I'll open a new Issue for that 😅
